"""Pre Base default

Revision ID: 6157c912737e
Revises: 20284b0804ba
Create Date: 2023-07-26 02:31:46.899623

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '6157c912737e'
down_revision = '20284b0804ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.alter_column('full_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('invested_amount',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('full_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('invested_amount',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('full_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('invested_amount',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('invested_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('full_amount',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('invested_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('full_amount',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.alter_column('invested_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('full_amount',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
