"""Pre Base default

Revision ID: cca8b6d2d035
Revises: 6157c912737e
Create Date: 2023-07-26 02:33:28.145404

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'cca8b6d2d035'
down_revision = '6157c912737e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
